DELETE FROM logs_mapping;
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (1, 'Restaurant', 'Receiving', 'Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (2, 'Restaurant', 'Preparation', 'Cleaning Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (3, 'Restaurant', 'Cooking / Baking', 'CCP Monitoring Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (4, 'Restaurant', 'Cooking / Baking', 'Cooking Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (5, 'Restaurant', 'Cooling', 'Cooling Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (6, 'Restaurant', 'Cold Holding', 'Cold Storage Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (7, 'Restaurant', 'Hot Holding', 'Hot Holding Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (8, 'Restaurant', 'Storage', 'Pest Control Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (9, 'Restaurant', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (10, 'Restaurant', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (11, 'Restaurant', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (12, 'Bakery', 'Receiving', 'Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (13, 'Bakery', 'Preparation', 'Cleaning Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (14, 'Bakery', 'Mixing', 'Grinding Control Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (15, 'Bakery', 'Cooking / Baking', 'Cooking Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (16, 'Bakery', 'Cooling', 'Cooling Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (17, 'Bakery', 'Packaging', 'Packaging Inspection Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (18, 'Bakery', 'Storage', 'Pest Control Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (19, 'Bakery', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (20, 'Bakery', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (21, 'Bakery', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (22, 'Catering', 'Receiving', 'Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (23, 'Catering', 'Preparation', 'Cleaning Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (24, 'Catering', 'Cooking / Baking', 'Cooking Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (25, 'Catering', 'Hot Holding', 'Hot Holding Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (26, 'Catering', 'Transportation', 'Hot Holding Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (27, 'Catering', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (28, 'Catering', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (29, 'Catering', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (30, 'Cloud Kitchen', 'Receiving', 'Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (31, 'Cloud Kitchen', 'Preparation', 'Cleaning Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (32, 'Cloud Kitchen', 'Cooking / Baking', 'Cooking Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (33, 'Cloud Kitchen', 'Hot Holding', 'Hot Holding Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (34, 'Cloud Kitchen', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (35, 'Cloud Kitchen', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (36, 'Cloud Kitchen', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (37, 'Dairy', 'Receiving', 'Milk Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (38, 'Dairy', 'Cold Holding', 'Milk Storage Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (39, 'Dairy', 'Processing', 'Pasteurization Temperature Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (40, 'Dairy', 'Processing', 'Pasteurization Time Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (41, 'Dairy', 'Processing', 'Fermentation pH Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (42, 'Dairy', 'Cleaning', 'CIP Cleaning Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (43, 'Dairy', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (44, 'Dairy', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (45, 'Dairy', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (46, 'Meat', 'Receiving', 'Meat Receiving Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (47, 'Meat', 'Receiving', 'Residue Testing Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (48, 'Meat', 'Cooling', 'Chilling Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (49, 'Meat', 'Cold Holding', 'Freezing Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (50, 'Meat', 'Preparation', 'Cutting Hygiene Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (51, 'Meat', 'Processing', 'Grinding Control Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (52, 'Meat', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (53, 'Meat', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (54, 'Meat', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (55, 'Beverage', 'Processing', 'Brix Level Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (56, 'Beverage', 'Processing', 'pH Monitoring Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (57, 'Beverage', 'Processing', 'Carbonation Pressure Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (58, 'Beverage', 'Packaging', 'Bottle Sterilization Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (59, 'Beverage', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (60, 'Beverage', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (61, 'Beverage', 'General', 'Training Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (62, 'Water', 'Processing', 'Turbidity Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (63, 'Water', 'Processing', 'TDS Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (64, 'Water', 'Processing', 'Microbial Testing Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (65, 'Water', 'Processing', 'Chlorination Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (66, 'Water', 'General', 'Corrective Action Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (67, 'Water', 'General', 'Internal Audit Log');
INSERT INTO logs_mapping (id, activity, process_step, log_name) VALUES (68, 'Water', 'General', 'Training Log');

DELETE FROM equipment_library;
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (1, 'Pasteurizer', 'Dairy', 'Pasteurization');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (2, 'Homogenizer', 'Dairy', 'Homogenization');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (3, 'Milk Storage Tank', 'Dairy', 'Cold Storage');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (4, 'Fermentation Tank', 'Dairy', 'Fermentation');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (5, 'Spray Dryer', 'Dairy', 'Drying (Spray Drying)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (6, 'Filling Machine', 'Dairy', 'Filling / Packaging');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (7, 'Cold Room', 'Dairy', 'Cold Storage');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (8, 'Freezer', 'Dairy', 'Frozen Storage');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (9, 'Meat Grinder', 'Meat', 'Mincing / Grinding');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (10, 'Cutting Table', 'Meat', 'Cutting / Deboning');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (11, 'Mixer', 'Meat', 'Mixing (Spices / Additives)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (12, 'Cooking Oven', 'Meat', 'Cooking / Heat Treatment');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (13, 'Blast Freezer', 'Meat', 'Freezing (IQF / Blast Freezing)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (14, 'Cold Room', 'Meat', 'Cold Storage');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (15, 'Metal Detector', 'Meat', 'Metal Detection');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (16, 'Packaging Machine', 'Meat', 'Packaging');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (17, 'Washing Unit', 'Beverage', 'Washing');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (18, 'Juice Extractor', 'Beverage', 'Juice Extraction');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (19, 'Mixing Tank', 'Beverage', 'Mixing / Blending');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (20, 'Pasteurizer', 'Beverage', 'Pasteurization');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (21, 'Carbonation Unit', 'Beverage', 'Carbonation (Soft Drinks)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (22, 'Filling Machine', 'Beverage', 'Filling');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (23, 'Cold Room', 'Beverage', 'Cold Storage');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (24, 'Raw Water Tank', 'Water', 'Raw Water Intake');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (25, 'Sand Filter', 'Water', 'Filtration (Sand / Carbon)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (26, 'Activated Carbon Filter', 'Water', 'Activated Carbon Filtration');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (27, 'RO System', 'Water', 'Reverse Osmosis (RO)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (28, 'pH Dosing Pump', 'Water', 'Chemical Dosing (pH Adjustment)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (29, 'Chlorination Unit', 'Water', 'Disinfection (Chlorination / UV / Ozone)');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (30, 'Storage Tank', 'Water', 'Storage Tank');
INSERT INTO equipment_library (id, equipment_name, activity_type, related_process) VALUES (31, 'Filling Machine', 'Water', 'Filling');

DELETE FROM prp_master;
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (1, 'Cleaning and Sanitation Program', 'Cleaning of food contact surfaces, equipment, and environment', 'Daily', 'Staff', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (2, 'Pest Control Program', 'Monitoring and control of pests in the facility', 'Weekly', 'Manager', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (3, 'Personal Hygiene Program', 'Staff hygiene practices including handwashing and protective clothing', 'Daily', 'Staff', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (4, 'Supplier Control Program', 'Approval and inspection of incoming suppliers and materials', 'Each Delivery', 'Manager', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (5, 'Waste Management Program', 'Handling and disposal of food waste and garbage', 'Daily', 'Staff', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (6, 'Equipment Maintenance Program', 'Preventive maintenance of equipment and tools', 'Monthly', 'Manager', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (7, 'Allergen Control Program', 'Prevention of allergen cross-contact', 'Daily', 'Staff', 'Core');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (8, 'Temperature Control Program', 'Monitoring and control of food and storage temperatures', 'Hourly', 'Staff', 'Manufacturing');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (9, 'Process Control Program', 'Monitoring of critical processing steps', 'Daily', 'Manager', 'Manufacturing');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (10, 'Water Quality Control Program', 'Monitoring water safety and quality', 'Daily', 'Manager', 'Manufacturing');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (11, 'Calibration Program', 'Calibration of thermometers and measuring devices', 'Monthly', 'Manager', 'Manufacturing');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (12, 'Traceability and Recall Program', 'Product traceability and recall procedures', 'As needed', 'Manager', 'Manufacturing');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (13, 'Document Control Program', 'Control and management of food safety documents', 'Monthly', 'Manager', 'System');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (14, 'Record Keeping Program', 'Management and storage of food safety records', 'Daily', 'Staff', 'System');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (15, 'Training Program', 'Staff training on food safety and HACCP', 'As needed', 'Manager', 'System');
INSERT INTO prp_master (id, program_name, description, frequency, responsible, category) VALUES (16, 'Internal Audit Program', 'Periodic internal audits of food safety system', 'Monthly', 'Manager', 'System');

DELETE FROM prp_mapping;
INSERT INTO prp_mapping (id, activity, program_name) VALUES (1, 'Restaurant', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (2, 'Restaurant', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (3, 'Restaurant', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (4, 'Restaurant', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (5, 'Restaurant', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (6, 'Restaurant', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (7, 'Restaurant', 'Allergen Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (8, 'Restaurant', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (9, 'Restaurant', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (10, 'Restaurant', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (11, 'Restaurant', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (12, 'Cafe', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (13, 'Cafe', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (14, 'Cafe', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (15, 'Cafe', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (16, 'Cafe', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (17, 'Cafe', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (18, 'Cafe', 'Allergen Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (19, 'Cafe', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (20, 'Cafe', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (21, 'Cafe', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (22, 'Cafe', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (23, 'Bakery', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (24, 'Bakery', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (25, 'Bakery', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (26, 'Bakery', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (27, 'Bakery', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (28, 'Bakery', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (29, 'Bakery', 'Allergen Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (30, 'Bakery', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (31, 'Bakery', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (32, 'Bakery', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (33, 'Bakery', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (34, 'Bakery', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (35, 'Juice Bar', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (36, 'Juice Bar', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (37, 'Juice Bar', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (38, 'Juice Bar', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (39, 'Juice Bar', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (40, 'Juice Bar', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (41, 'Juice Bar', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (42, 'Juice Bar', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (43, 'Juice Bar', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (44, 'Juice Bar', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (45, 'Juice Bar', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (46, 'Ice Cream Shop', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (47, 'Ice Cream Shop', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (48, 'Ice Cream Shop', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (49, 'Ice Cream Shop', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (50, 'Ice Cream Shop', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (51, 'Ice Cream Shop', 'Allergen Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (52, 'Ice Cream Shop', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (53, 'Ice Cream Shop', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (54, 'Ice Cream Shop', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (55, 'Ice Cream Shop', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (56, 'Ice Cream Shop', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (57, 'Catering', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (58, 'Catering', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (59, 'Catering', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (60, 'Catering', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (61, 'Catering', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (62, 'Catering', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (63, 'Catering', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (64, 'Catering', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (65, 'Catering', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (66, 'Catering', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (67, 'Catering', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (68, 'Cloud Kitchen', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (69, 'Cloud Kitchen', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (70, 'Cloud Kitchen', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (71, 'Cloud Kitchen', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (72, 'Cloud Kitchen', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (73, 'Cloud Kitchen', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (74, 'Cloud Kitchen', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (75, 'Cloud Kitchen', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (76, 'Cloud Kitchen', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (77, 'Cloud Kitchen', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (78, 'Cloud Kitchen', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (79, 'Dairy', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (80, 'Dairy', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (81, 'Dairy', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (82, 'Dairy', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (83, 'Dairy', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (84, 'Dairy', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (85, 'Dairy', 'Allergen Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (86, 'Dairy', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (87, 'Dairy', 'Process Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (88, 'Dairy', 'Water Quality Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (89, 'Dairy', 'Calibration Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (90, 'Dairy', 'Traceability and Recall Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (91, 'Dairy', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (92, 'Dairy', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (93, 'Dairy', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (94, 'Dairy', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (95, 'Meat', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (96, 'Meat', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (97, 'Meat', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (98, 'Meat', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (99, 'Meat', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (100, 'Meat', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (101, 'Meat', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (102, 'Meat', 'Process Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (103, 'Meat', 'Calibration Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (104, 'Meat', 'Traceability and Recall Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (105, 'Meat', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (106, 'Meat', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (107, 'Meat', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (108, 'Meat', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (109, 'Beverage', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (110, 'Beverage', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (111, 'Beverage', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (112, 'Beverage', 'Supplier Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (113, 'Beverage', 'Waste Management Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (114, 'Beverage', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (115, 'Beverage', 'Temperature Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (116, 'Beverage', 'Process Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (117, 'Beverage', 'Water Quality Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (118, 'Beverage', 'Calibration Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (119, 'Beverage', 'Traceability and Recall Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (120, 'Beverage', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (121, 'Beverage', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (122, 'Beverage', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (123, 'Beverage', 'Internal Audit Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (124, 'Water', 'Cleaning and Sanitation Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (125, 'Water', 'Pest Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (126, 'Water', 'Personal Hygiene Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (127, 'Water', 'Equipment Maintenance Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (128, 'Water', 'Water Quality Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (129, 'Water', 'Process Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (130, 'Water', 'Calibration Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (131, 'Water', 'Traceability and Recall Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (132, 'Water', 'Document Control Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (133, 'Water', 'Record Keeping Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (134, 'Water', 'Training Program');
INSERT INTO prp_mapping (id, activity, program_name) VALUES (135, 'Water', 'Internal Audit Program');

DELETE FROM sop_master;
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (1, 'Receiving Inspection Procedure', 'Receiving', 'Ensure all incoming materials meet safety standards', 'All incoming food and materials', '1. Check supplier approval 2. Inspect packaging 3. Check temperature if required 4. Accept or reject materials', 'Each Delivery', 'Staff', 'Supplier Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (2, 'Cold Storage Procedure', 'Cold Holding', 'Maintain safe storage temperature', 'All refrigerated storage', '1. Store food below 5°C 2. Monitor temperature 3. Record readings 4. Report deviations', 'Hourly', 'Staff', 'Temperature Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (3, 'Hot Holding Procedure', 'Hot Holding', 'Keep food at safe hot holding temperature', 'All hot holding equipment', '1. Maintain temperature above 60°C 2. Monitor regularly 3. Record temperature', 'Hourly', 'Staff', 'Temperature Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (4, 'Cooking Temperature Control Procedure', 'Cooking / Baking', 'Ensure food is cooked safely', 'All cooking processes', '1. Cook food to at least 75°C 2. Measure temperature 3. Record results', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (5, 'Cooling Procedure', 'Cooling', 'Ensure safe cooling of cooked food', 'All cooling processes', '1. Cool food from 60°C to 5°C within 6 hours 2. Monitor time and temperature', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (6, 'Reheating Procedure', 'Reheating', 'Ensure safe reheating of food', 'All reheating processes', '1. Reheat food to at least 75°C 2. Record temperature', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (7, 'Cleaning and Sanitation Procedure', 'Preparation', 'Maintain cleanliness of equipment and surfaces', 'All food contact surfaces', '1. Remove debris 2. Wash with detergent 3. Rinse 4. Sanitize 5. Air dry', 'Daily', 'Staff', 'Cleaning and Sanitation Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (8, 'Personal Hygiene Procedure', 'Preparation', 'Ensure staff hygiene compliance', 'All staff handling food', '1. Wash hands regularly 2. Wear clean uniform 3. Use gloves when required', 'Daily', 'Staff', 'Personal Hygiene Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (9, 'Pest Control Procedure', 'Storage', 'Prevent pest contamination', 'All facility areas', '1. Inspect facility 2. Use traps 3. Record pest activity', 'Weekly', 'Manager', 'Pest Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (10, 'Waste Management Procedure', 'General', 'Ensure proper waste handling', 'All waste areas', '1. Separate waste 2. Dispose daily 3. Clean bins', 'Daily', 'Staff', 'Waste Management Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (11, 'Equipment Maintenance Procedure', 'General', 'Maintain equipment in good condition', 'All equipment', '1. Perform scheduled maintenance 2. Report faults', 'Monthly', 'Manager', 'Equipment Maintenance Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (12, 'Allergen Control Procedure', 'Preparation', 'Prevent allergen cross contact', 'All food preparation areas', '1. Separate allergen materials 2. Clean equipment 3. Label properly', 'Daily', 'Staff', 'Allergen Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (13, 'Internal Audit Procedure', 'General', 'Verify food safety system compliance', 'All processes', '1. Conduct audit 2. Record findings 3. Take corrective action', 'Monthly', 'Manager', 'Internal Audit Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (14, 'Training Procedure', 'General', 'Ensure staff are trained in food safety', 'All staff', '1. Conduct training sessions 2. Record attendance', 'As needed', 'Manager', 'Training Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (15, 'Document Control Procedure', 'General', 'Control all food safety documents', 'All documents', '1. Approve documents 2. Update regularly 3. Archive old versions', 'Monthly', 'Manager', 'Document Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (16, 'Record Keeping Procedure', 'General', 'Maintain proper records', 'All logs and records', '1. Record data accurately 2. Store records securely', 'Daily', 'Staff', 'Record Keeping Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (17, 'Pasteurization Procedure', 'Processing', 'Ensure safe pasteurization process', 'Dairy and beverage processing', '1. Heat to required temperature 2. Maintain time 3. Record parameters', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (18, 'Fermentation Control Procedure', 'Processing', 'Control fermentation process', 'Dairy and beverage products', '1. Monitor pH 2. Control time 3. Record results', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (19, 'Meat Processing Hygiene Procedure', 'Preparation', 'Ensure hygienic meat processing', 'Meat processing areas', '1. Clean surfaces 2. Avoid cross contamination 3. Maintain hygiene', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (20, 'Chilling Procedure', 'Cooling', 'Ensure proper chilling of products', 'Meat and processed food', '1. Rapidly cool products 2. Monitor temperature 3. Record results', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (21, 'Freezing Procedure', 'Cold Holding', 'Ensure proper freezing conditions', 'Frozen products', '1. Maintain freezing temperature 2. Monitor and record', 'Each batch', 'Staff', 'Process Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (22, 'Water Quality Control Procedure', 'Processing', 'Ensure water safety', 'Water and beverage systems', '1. Test water quality 2. Monitor parameters 3. Record results', 'Daily', 'Manager', 'Water Quality Control Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (23, 'Calibration Procedure', 'General', 'Ensure accuracy of measuring devices', 'All measuring equipment', '1. Calibrate regularly 2. Record calibration results', 'Monthly', 'Manager', 'Calibration Program');
INSERT INTO sop_master (id, sop_name, process_step, purpose, scope, procedure_text, frequency, responsible, related_prp) VALUES (24, 'Traceability and Recall Procedure', 'General', 'Ensure product traceability and recall capability', 'All products', '1. Assign batch codes 2. Track products 3. Recall if needed', 'As needed', 'Manager', 'Traceability and Recall Program');

DELETE FROM fsms_documents;
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (1, 'Food Safety Policy', 'The organization is committed to producing safe food by implementing HACCP principles, maintaining hygiene standards, and complying with food safety regulations', 'Owner');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (2, 'Food Safety Objectives', 'The organization aims to maintain safe food production, monitor critical control points, and continuously improve food safety performance', 'Owner');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (3, 'HACCP Team', 'The HACCP team is responsible for developing, implementing, and maintaining the HACCP system within the organization', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (4, 'Product Description', 'Description of food products including ingredients, storage conditions, and shelf life', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (5, 'Intended Use', 'Description of how the food product is expected to be used by consumers', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (6, 'Flow Diagram Verification', 'Procedure for verifying that the process flow diagram accurately represents the food preparation process', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (7, 'HACCP Verification Procedure', 'Procedures used to verify that the HACCP system is working effectively', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (8, 'Record Keeping Procedure', 'Procedure for maintaining and storing food safety records and monitoring logs', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (9, 'Corrective Action Procedure', 'Steps taken when monitoring results indicate a deviation from critical limits', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (10, 'Internal Audit Procedure', 'Procedure for conducting internal food safety audits within the organization', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (11, 'Product Recall Procedure', 'Procedure for identifying, tracing, and removing unsafe or non-compliant food products from sale or distribution. The organization will immediately stop using the affected product, isolate the batch, inform management, and take corrective actions to protect consumer safety. Records of the recall and actions taken will be maintained.', 'Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (12, 'Supplier Approval Procedure', 'Procedure for evaluating, approving, and monitoring suppliers to ensure raw material safety and compliance', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (13, 'Approved Supplier List', 'List of approved suppliers who meet food safety and quality requirements', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (14, 'Raw Material Specification', 'Specifications for raw materials including safety, quality, and acceptance criteria', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (15, 'Traceability Procedure', 'Procedure for tracking raw materials and finished products through all stages of production', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (16, 'Batch Coding System', 'System for assigning batch numbers to products for identification and traceability', 'Production Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (17, 'Product Identification Procedure', 'Procedure for labeling and identifying products throughout production and distribution', 'Production Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (18, 'Allergen Control Procedure', 'Procedure for identifying, managing, and preventing allergen cross-contact', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (19, 'Allergen Risk Assessment', 'Assessment of allergen risks associated with raw materials and processing steps', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (20, 'Allergen Cleaning Validation', 'Procedure for validating cleaning effectiveness to remove allergen residues', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (21, 'Calibration Procedure', 'Procedure for calibrating equipment such as thermometers, pH meters, and sensors', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (22, 'Calibration Records Template', 'Template for recording calibration results and maintaining equipment accuracy', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (23, 'Equipment Verification Procedure', 'Procedure to verify equipment performance and functionality before use', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (24, 'Preventive Maintenance Procedure', 'Procedure for scheduled maintenance to ensure equipment reliability', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (25, 'Equipment Maintenance Log', 'Log for recording maintenance activities and equipment repairs', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (26, 'Breakdown Handling Procedure', 'Procedure for managing equipment breakdowns and minimizing production risks', 'Maintenance Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (27, 'Cleaning and Sanitation Procedure', 'Procedure for cleaning and sanitizing equipment and facilities', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (28, 'Cleaning Schedule', 'Schedule for routine cleaning and sanitation activities', 'Production Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (29, 'Chemical Control Procedure', 'Procedure for handling, storing, and using cleaning chemicals safely', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (30, 'Pest Control Procedure', 'Procedure for monitoring and controlling pests within the facility', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (31, 'Pest Monitoring Records', 'Records of pest control inspections and corrective actions', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (32, 'Training Procedure', 'Procedure for training staff on food safety and operational practices', 'HR / Training Officer');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (33, 'Competency Assessment', 'Procedure for evaluating staff competence and performance', 'HR / Training Officer');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (34, 'Training Plan', 'Planned schedule of training activities for employees', 'HR / Training Officer');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (35, 'Non-Conformance Procedure', 'Procedure for identifying and managing non-conforming products or processes', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (36, 'Product Hold & Release Procedure', 'Procedure for holding and releasing products based on quality and safety checks', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (37, 'Document Control Procedure', 'Procedure for managing and updating documents within the system', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (38, 'Record Control Procedure', 'Procedure for maintaining and storing records securely and effectively', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (39, 'Risk Assessment Procedure', 'Procedure for assessing risks related to food safety hazards', 'QA Manager');
INSERT INTO fsms_documents (id, document_name, description, responsible) VALUES (40, 'Hazard Evaluation Methodology', 'Methodology used to evaluate hazards based on severity and likelihood', 'QA Manager');

SELECT setval('logs_mapping_id_seq', COALESCE((SELECT MAX(id) FROM logs_mapping), 0) + 1, false);
SELECT setval('equipment_library_id_seq', COALESCE((SELECT MAX(id) FROM equipment_library), 0) + 1, false);
SELECT setval('prp_master_id_seq', COALESCE((SELECT MAX(id) FROM prp_master), 0) + 1, false);
SELECT setval('prp_mapping_id_seq', COALESCE((SELECT MAX(id) FROM prp_mapping), 0) + 1, false);
SELECT setval('sop_master_id_seq', COALESCE((SELECT MAX(id) FROM sop_master), 0) + 1, false);
SELECT setval('fsms_documents_id_seq', COALESCE((SELECT MAX(id) FROM fsms_documents), 0) + 1, false);