-- Batch 1: Templates, Activities, Process Steps, Activity Process Map, Hazard Library
DELETE FROM templates;
INSERT INTO templates (id, template_name, description, industry_scope) VALUES (1, 'Food Service', 'Restaurants and food outlets', 'Restaurant Operations');
INSERT INTO templates (id, template_name, description, industry_scope) VALUES (2, 'Bakery', 'Bakery and pastry production', 'Bakery Production');
INSERT INTO templates (id, template_name, description, industry_scope) VALUES (3, 'Manufacturing', 'dairy, meat, juice, and water processing', 'Food Manufacturing');

DELETE FROM activity_types;
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (1, 'Food Service', 'Restaurant', 'Food Service');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (2, 'Food Service', 'Cafe', 'Food Service');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (3, 'Food Service', 'Juice Bar', 'Beverage');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (4, 'Food Service', 'Ice Cream Shop', 'Dessert');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (5, 'Food Service', 'Catering', 'Food Service');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (6, 'Food Service', 'Cloud Kitchen', 'Food Service');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (7, 'Bakery', 'Bakery', 'Bakery');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (8, 'Bakery', 'Pastry Shop', 'Bakery');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (9, 'Manufacturing', 'Dairy Processing', 'Dairy');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (10, 'Manufacturing', 'Water Treatment', 'Water');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (11, 'Manufacturing', 'Juice & Beverage Processing', 'Beverage');
INSERT INTO activity_types (id, template, activity_name, industry_type) VALUES (12, 'Manufacturing', 'Meat Processing', 'Meat');

DELETE FROM process_steps;
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (1, 'Receiving', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (2, 'Storage', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (3, 'Cold Storage', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (4, 'Frozen Storage', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (5, 'Washing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (6, 'Preparation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (7, 'Thawing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (8, 'Cutting / Deboning', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (9, 'Trimming', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (10, 'Grinding / Mincing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (11, 'Mixing / Blending', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (12, 'Addition of Ingredients', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (13, 'Forming / Shaping', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (14, 'Marination', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (15, 'Curing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (16, 'Cooking / Baking', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (17, 'Pasteurization', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (18, 'UHT Processing', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (19, 'Cooling', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (20, 'Hot Holding', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (21, 'Cold Holding', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (22, 'Reheating', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (23, 'Fermentation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (24, 'Coagulation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (25, 'Separation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (26, 'Homogenization', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (27, 'Evaporation / Concentration', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (28, 'Drying', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (29, 'Filling', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (30, 'Packaging', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (31, 'Capping / Sealing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (32, 'Labeling', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (33, 'Metal Detection', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (34, 'Weighing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (35, 'Serving', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (36, 'Transportation', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (37, 'Distribution', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (38, 'Water Intake', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (39, 'Pre-Filtration', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (40, 'Coagulation (Water)', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (41, 'Flocculation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (42, 'Sedimentation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (43, 'Filtration', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (44, 'Activated Carbon Filtration', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (45, 'Reverse Osmosis (RO)', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (46, 'Softening', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (47, 'Chemical Dosing (pH Adjustment)', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (48, 'Disinfection (Chlorination / UV / Ozone)', 'CCP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (49, 'Dechlorination', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (50, 'Water Storage', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (51, 'Final Filtration', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (52, 'Juice Extraction', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (53, 'Sorting / Grading', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (54, 'Peeling', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (55, 'Carbonation', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (56, 'Freezing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (57, 'Glazing', 'PRP');
INSERT INTO process_steps (id, process_name, default_step_type) VALUES (58, 'Aging / Ripening', 'PRP');

DELETE FROM activity_process_map;
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (1, 'Restaurant', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (2, 'Restaurant', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (3, 'Restaurant', 'Washing', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (4, 'Restaurant', 'Thawing', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (5, 'Restaurant', 'Preparation', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (6, 'Restaurant', 'Cooking / Baking', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (7, 'Restaurant', 'Cooling', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (8, 'Restaurant', 'Cold Holding', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (9, 'Restaurant', 'Hot Holding', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (10, 'Restaurant', 'Reheating', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (11, 'Restaurant', 'Serving', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (12, 'Cafe', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (13, 'Cafe', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (14, 'Cafe', 'Preparation', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (15, 'Cafe', 'Mixing / Blending', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (16, 'Cafe', 'Cooking / Baking', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (17, 'Cafe', 'Hot Holding', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (18, 'Cafe', 'Cold Holding', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (19, 'Cafe', 'Serving', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (20, 'Juice Bar', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (21, 'Juice Bar', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (22, 'Juice Bar', 'Washing', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (23, 'Juice Bar', 'Preparation', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (24, 'Juice Bar', 'Mixing / Blending', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (25, 'Juice Bar', 'Cold Holding', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (26, 'Juice Bar', 'Serving', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (27, 'Ice Cream Shop', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (28, 'Ice Cream Shop', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (29, 'Ice Cream Shop', 'Washing', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (30, 'Ice Cream Shop', 'Preparation', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (31, 'Ice Cream Shop', 'Mixing / Blending', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (32, 'Ice Cream Shop', 'Cold Holding', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (33, 'Ice Cream Shop', 'Serving', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (34, 'Catering', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (35, 'Catering', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (36, 'Catering', 'Washing', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (37, 'Catering', 'Thawing', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (38, 'Catering', 'Preparation', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (39, 'Catering', 'Cooking / Baking', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (40, 'Catering', 'Cooling', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (41, 'Catering', 'Cold Holding', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (42, 'Catering', 'Packaging', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (43, 'Catering', 'Transportation', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (44, 'Catering', 'Reheating', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (45, 'Catering', 'Hot Holding', 12);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (46, 'Catering', 'Serving', 13);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (47, 'Cloud Kitchen', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (48, 'Cloud Kitchen', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (49, 'Cloud Kitchen', 'Washing', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (50, 'Cloud Kitchen', 'Thawing', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (51, 'Cloud Kitchen', 'Preparation', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (52, 'Cloud Kitchen', 'Cooking / Baking', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (53, 'Cloud Kitchen', 'Cooling', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (54, 'Cloud Kitchen', 'Cold Holding', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (55, 'Cloud Kitchen', 'Hot Holding', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (56, 'Cloud Kitchen', 'Packaging', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (57, 'Cloud Kitchen', 'Serving', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (58, 'Bakery', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (59, 'Bakery', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (60, 'Bakery', 'Preparation', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (61, 'Bakery', 'Mixing / Blending', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (62, 'Bakery', 'Cooking / Baking', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (63, 'Bakery', 'Cooling', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (64, 'Bakery', 'Cold Holding', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (65, 'Bakery', 'Packaging', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (66, 'Bakery', 'Serving', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (67, 'Pastry Shop', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (68, 'Pastry Shop', 'Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (69, 'Pastry Shop', 'Preparation', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (70, 'Pastry Shop', 'Mixing / Blending', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (71, 'Pastry Shop', 'Cooking / Baking', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (72, 'Pastry Shop', 'Cooling', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (73, 'Pastry Shop', 'Cold Holding', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (74, 'Pastry Shop', 'Packaging', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (75, 'Pastry Shop', 'Serving', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (76, 'Dairy Processing', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (77, 'Dairy Processing', 'Filtration', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (78, 'Dairy Processing', 'Separation', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (79, 'Dairy Processing', 'Homogenization', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (80, 'Dairy Processing', 'Pasteurization', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (81, 'Dairy Processing', 'Cooling', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (82, 'Dairy Processing', 'Fermentation', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (83, 'Dairy Processing', 'Coagulation', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (84, 'Dairy Processing', 'Cutting / Deboning', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (85, 'Dairy Processing', 'Separation', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (86, 'Dairy Processing', 'Aging / Ripening', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (87, 'Dairy Processing', 'Mixing / Blending', 12);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (88, 'Dairy Processing', 'Addition of Ingredients', 13);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (89, 'Dairy Processing', 'Evaporation / Concentration', 14);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (90, 'Dairy Processing', 'Drying', 15);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (91, 'Dairy Processing', 'Filling', 16);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (92, 'Dairy Processing', 'Packaging', 17);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (93, 'Dairy Processing', 'Cold Storage', 18);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (94, 'Dairy Processing', 'Frozen Storage', 19);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (95, 'Dairy Processing', 'Distribution', 20);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (96, 'Meat Processing', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (97, 'Meat Processing', 'Cold Storage', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (98, 'Meat Processing', 'Frozen Storage', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (99, 'Meat Processing', 'Thawing', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (100, 'Meat Processing', 'Cutting / Deboning', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (101, 'Meat Processing', 'Trimming', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (102, 'Meat Processing', 'Washing', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (103, 'Meat Processing', 'Grinding / Mincing', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (104, 'Meat Processing', 'Mixing / Blending', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (105, 'Meat Processing', 'Forming / Shaping', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (106, 'Meat Processing', 'Marination', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (107, 'Meat Processing', 'Curing', 12);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (108, 'Meat Processing', 'Cooking / Baking', 13);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (109, 'Meat Processing', 'Cooling', 14);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (110, 'Meat Processing', 'Freezing', 15);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (111, 'Meat Processing', 'Metal Detection', 16);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (112, 'Meat Processing', 'Weighing', 17);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (113, 'Meat Processing', 'Packaging', 18);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (114, 'Meat Processing', 'Labeling', 19);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (115, 'Meat Processing', 'Cold Storage', 20);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (116, 'Meat Processing', 'Frozen Storage', 21);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (117, 'Meat Processing', 'Distribution', 22);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (118, 'Juice & Beverage Processing', 'Receiving', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (119, 'Juice & Beverage Processing', 'Washing', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (120, 'Juice & Beverage Processing', 'Sorting / Grading', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (121, 'Juice & Beverage Processing', 'Peeling', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (122, 'Juice & Beverage Processing', 'Cutting', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (123, 'Juice & Beverage Processing', 'Juice Extraction', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (124, 'Juice & Beverage Processing', 'Filtration', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (125, 'Juice & Beverage Processing', 'Mixing / Blending', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (126, 'Juice & Beverage Processing', 'Addition of Ingredients', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (127, 'Juice & Beverage Processing', 'Pasteurization', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (128, 'Juice & Beverage Processing', 'Homogenization', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (129, 'Juice & Beverage Processing', 'Carbonation', 12);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (130, 'Juice & Beverage Processing', 'Cooling', 13);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (131, 'Juice & Beverage Processing', 'Filling', 14);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (132, 'Juice & Beverage Processing', 'Capping / Sealing', 15);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (133, 'Juice & Beverage Processing', 'Labeling', 16);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (134, 'Juice & Beverage Processing', 'Packaging', 17);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (135, 'Juice & Beverage Processing', 'Cold Storage', 18);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (136, 'Juice & Beverage Processing', 'Storage', 19);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (137, 'Juice & Beverage Processing', 'Distribution', 20);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (138, 'Water Treatment', 'Water Intake', 1);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (139, 'Water Treatment', 'Pre-Filtration', 2);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (140, 'Water Treatment', 'Coagulation (Water)', 3);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (141, 'Water Treatment', 'Flocculation', 4);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (142, 'Water Treatment', 'Sedimentation', 5);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (143, 'Water Treatment', 'Filtration', 6);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (144, 'Water Treatment', 'Activated Carbon Filtration', 7);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (145, 'Water Treatment', 'Reverse Osmosis (RO)', 8);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (146, 'Water Treatment', 'Softening', 9);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (147, 'Water Treatment', 'Chemical Dosing (pH Adjustment)', 10);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (148, 'Water Treatment', 'Disinfection (Chlorination / UV / Ozone)', 11);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (149, 'Water Treatment', 'Dechlorination', 12);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (150, 'Water Treatment', 'Water Storage', 13);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (151, 'Water Treatment', 'Final Filtration', 14);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (152, 'Water Treatment', 'Filling', 15);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (153, 'Water Treatment', 'Capping / Sealing', 16);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (154, 'Water Treatment', 'Labeling', 17);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (155, 'Water Treatment', 'Packaging', 18);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (156, 'Water Treatment', 'Storage', 19);
INSERT INTO activity_process_map (id, activity, process, process_order) VALUES (157, 'Water Treatment', 'Distribution', 20);

DELETE FROM hazard_library;
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (1, 'Salmonella', 'Biological', 'Receiving | Cooking | Washing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (2, 'Listeria monocytogenes', 'Biological', 'Cold Storage | Ready-to-eat');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (3, 'E. coli', 'Biological', 'Washing | Raw Materials');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (4, 'Staphylococcus aureus', 'Biological', 'Preparation | Handling');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (5, 'Bacillus cereus', 'Biological', 'Cooking | Cooling');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (6, 'Clostridium perfringens', 'Biological', 'Cooking | Hot Holding');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (7, 'Campylobacter', 'Biological', 'Raw Meat Handling');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (8, 'Norovirus', 'Biological', 'Handling | Ready-to-eat');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (9, 'Hepatitis A virus', 'Biological', 'Handling | Ready-to-eat');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (10, 'Clostridium botulinum', 'Biological', 'Anaerobic | Canning');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (11, 'Yeasts & molds', 'Biological', 'Storage | Fermentation');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (12, 'Cross-contamination', 'Biological', 'Preparation | Processing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (13, 'Temperature abuse', 'Biological', 'Holding | Storage');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (14, 'Post contamination', 'Biological', 'Packaging | Filling');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (15, 'Contaminated water', 'Biological', 'Washing | Water Supply');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (16, 'Clostridium spp.', 'Biological', 'Cooling | Processing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (17, 'Parasites (Trichinella)', 'Biological', 'Raw Meat');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (18, 'Spore-forming bacteria', 'Biological', 'Pasteurization | Cooking');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (19, 'Total coliforms', 'Biological', 'Water');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (20, 'Protozoa (Giardia, Cryptosporidium)', 'Biological', 'Water Treatment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (21, 'Biofilm formation', 'Biological', 'Equipment | Tanks');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (22, 'Algae growth', 'Biological', 'Water Storage');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (23, 'Cleaning chemical residues', 'Chemical', 'Equipment Cleaning');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (24, 'Sanitizer residues', 'Chemical', 'Equipment Cleaning');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (25, 'Pesticide residues', 'Chemical', 'Raw Materials');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (26, 'Allergens', 'Chemical', 'Preparation | Mixing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (27, 'Lubricant contamination', 'Chemical', 'Equipment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (28, 'Packaging chemical migration', 'Chemical', 'Packaging');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (29, 'Food additives (excess)', 'Chemical', 'Mixing | Formulation');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (30, 'Heavy metals', 'Chemical', 'Raw Materials | Water');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (31, 'Mycotoxins', 'Chemical', 'Storage');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (32, 'Antibiotic residues', 'Chemical', 'Raw Meat | Milk');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (33, 'Aflatoxin M1', 'Chemical', 'Milk');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (34, 'Nitrate / nitrite', 'Chemical', 'Water | Processing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (35, 'Chlorine (excess)', 'Chemical', 'Water Treatment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (36, 'Chemical dosing error', 'Chemical', 'Water Treatment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (37, 'Activated carbon fines', 'Chemical', 'Filtration');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (38, 'Membrane failure (RO)', 'Chemical', 'Water Treatment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (39, 'Hormone residues', 'Chemical', 'Raw Meat');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (40, 'CIP failure', 'Chemical', 'Cleaning');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (41, 'Water hardness', 'Chemical', 'Water Treatment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (42, 'Metal fragments', 'Physical', 'Equipment | Processing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (43, 'Glass fragments', 'Physical', 'Packaging | Facility');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (44, 'Plastic fragments', 'Physical', 'Packaging');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (45, 'Stones', 'Physical', 'Raw Materials');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (46, 'Bone fragments', 'Physical', 'Meat Processing');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (47, 'Wood fragments', 'Physical', 'Facility');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (48, 'Rubber fragments', 'Physical', 'Equipment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (49, 'Hair contamination', 'Physical', 'Handling');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (50, 'Insects', 'Physical', 'Environment');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (51, 'Foreign matter', 'Physical', 'General');
INSERT INTO hazard_library (id, hazard_name, hazard_type, typical_process) VALUES (52, 'Microplastics', 'Physical', 'Water');

SELECT setval('templates_id_seq', COALESCE((SELECT MAX(id) FROM templates), 0) + 1, false);
SELECT setval('activity_types_id_seq', COALESCE((SELECT MAX(id) FROM activity_types), 0) + 1, false);
SELECT setval('process_steps_id_seq', COALESCE((SELECT MAX(id) FROM process_steps), 0) + 1, false);
SELECT setval('activity_process_map_id_seq', COALESCE((SELECT MAX(id) FROM activity_process_map), 0) + 1, false);
SELECT setval('hazard_library_id_seq', COALESCE((SELECT MAX(id) FROM hazard_library), 0) + 1, false);