
INSERT INTO public.logs_unified (log_id, log_name, process_step, field_name, field_type, parameter, unit, frequency, required, log_category, applicable_activities) VALUES
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Date', 'Date', '-', '-', 'Each batch', true, 'Core', 'All'),
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Process', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Critical Limit', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Measured Value', 'Number', 'Temperature', '°C', 'Each batch', true, 'Core', 'All'),
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Status', 'Dropdown', '-', '-', 'Each batch', true, 'Core', 'All'),
(1, 'CCP Monitoring Log', 'Cooking / Baking', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(2, 'Cooking Temperature Log', 'Cooking / Baking', 'Date', 'Date', '-', '-', 'Each batch', true, 'Core', 'All'),
(2, 'Cooking Temperature Log', 'Cooking / Baking', 'Product', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(2, 'Cooking Temperature Log', 'Cooking / Baking', 'Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Core', 'All'),
(2, 'Cooking Temperature Log', 'Cooking / Baking', 'Time', 'Time', 'Time', 'Minutes', 'Each batch', true, 'Core', 'All'),
(2, 'Cooking Temperature Log', 'Cooking / Baking', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(3, 'Cooling Log', 'Cooling', 'Date', 'Date', '-', '-', 'Each batch', true, 'Core', 'All'),
(3, 'Cooling Log', 'Cooling', 'Start Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Core', 'All'),
(3, 'Cooling Log', 'Cooling', 'Final Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Core', 'All'),
(3, 'Cooling Log', 'Cooling', 'Time', 'Time', 'Time', 'Hours', 'Each batch', true, 'Core', 'All'),
(3, 'Cooling Log', 'Cooling', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(4, 'Cold Storage Log', 'Cold Holding', 'Date', 'Date', '-', '-', 'Hourly', true, 'Core', 'All'),
(4, 'Cold Storage Log', 'Cold Holding', 'Equipment', 'Select', '-', '-', 'Hourly', true, 'Core', 'All'),
(4, 'Cold Storage Log', 'Cold Holding', 'Temperature', 'Number', 'Temperature', '°C', 'Hourly', true, 'Core', 'All'),
(4, 'Cold Storage Log', 'Cold Holding', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Core', 'All'),
(5, 'Hot Holding Log', 'Hot Holding', 'Date', 'Date', '-', '-', 'Hourly', true, 'Core', 'All'),
(5, 'Hot Holding Log', 'Hot Holding', 'Temperature', 'Number', 'Temperature', '°C', 'Hourly', true, 'Core', 'All'),
(5, 'Hot Holding Log', 'Hot Holding', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Core', 'All'),
(6, 'Receiving Log', 'Receiving', 'Date', 'Date', '-', '-', 'Each batch', true, 'Core', 'All'),
(6, 'Receiving Log', 'Receiving', 'Supplier', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(6, 'Receiving Log', 'Receiving', 'Product', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(6, 'Receiving Log', 'Receiving', 'Status', 'Dropdown', '-', '-', 'Each batch', true, 'Core', 'All'),
(6, 'Receiving Log', 'Receiving', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(7, 'Cleaning Log', 'Preparation', 'Date', 'Date', '-', '-', 'Daily', true, 'Core', 'All'),
(7, 'Cleaning Log', 'Preparation', 'Area', 'Text', '-', '-', 'Daily', true, 'Core', 'All'),
(7, 'Cleaning Log', 'Preparation', 'Staff', 'Text', '-', '-', 'Daily', true, 'Core', 'All'),
(8, 'Pest Control Log', 'Storage', 'Date', 'Date', '-', '-', 'Weekly', true, 'Core', 'All'),
(8, 'Pest Control Log', 'Storage', 'Location', 'Text', '-', '-', 'Weekly', true, 'Core', 'All'),
(8, 'Pest Control Log', 'Storage', 'Action Taken', 'Text', '-', '-', 'Weekly', true, 'Core', 'All'),
(8, 'Pest Control Log', 'Storage', 'Staff', 'Text', '-', '-', 'Weekly', true, 'Core', 'All'),
(9, 'Corrective Action Log', 'General', 'Date', 'Date', '-', '-', 'As needed', true, 'Core', 'All'),
(9, 'Corrective Action Log', 'General', 'Issue', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(9, 'Corrective Action Log', 'General', 'Action Taken', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(9, 'Corrective Action Log', 'General', 'Responsible Person', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(10, 'Internal Audit Log', 'General', 'Date', 'Date', '-', '-', 'Monthly', true, 'Core', 'All'),
(10, 'Internal Audit Log', 'General', 'Findings', 'Text', '-', '-', 'Monthly', true, 'Core', 'All'),
(10, 'Internal Audit Log', 'General', 'Auditor', 'Text', '-', '-', 'Monthly', true, 'Core', 'All'),
(11, 'Training Log', 'General', 'Date', 'Date', '-', '-', 'As needed', true, 'Core', 'All'),
(11, 'Training Log', 'General', 'Staff Name', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(11, 'Training Log', 'General', 'Training Topic', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(11, 'Training Log', 'General', 'Trainer', 'Text', '-', '-', 'As needed', true, 'Core', 'All'),
(20, 'Milk Receiving Log', 'Receiving', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(20, 'Milk Receiving Log', 'Receiving', 'Quality Check', 'Text', 'Chemical / Physical', NULL, 'Each batch', true, 'Advanced', 'Dairy'),
(20, 'Milk Receiving Log', 'Receiving', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(21, 'Milk Storage Temperature Log', 'Cold Holding', 'Date', 'Date', '-', '-', 'Hourly', true, 'Advanced', 'Dairy'),
(21, 'Milk Storage Temperature Log', 'Cold Holding', 'Temperature', 'Number', 'Temperature', '°C', 'Hourly', true, 'Advanced', 'Dairy'),
(21, 'Milk Storage Temperature Log', 'Cold Holding', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Advanced', 'Dairy'),
(22, 'Pasteurization Temperature Log', 'Processing', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(22, 'Pasteurization Temperature Log', 'Processing', 'Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Advanced', 'Dairy'),
(22, 'Pasteurization Temperature Log', 'Processing', 'Time', 'Time', 'Time', 'Seconds', 'Each batch', true, 'Advanced', 'Dairy'),
(22, 'Pasteurization Temperature Log', 'Processing', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(23, 'Fermentation pH Log', 'Processing', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(23, 'Fermentation pH Log', 'Processing', 'pH Level', 'Number', 'pH', 'pH', 'Each batch', true, 'Advanced', 'Dairy'),
(23, 'Fermentation pH Log', 'Processing', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Dairy'),
(24, 'CIP Cleaning Log', 'Cleaning', 'Date', 'Date', '-', '-', 'Daily', true, 'Advanced', 'Dairy'),
(24, 'CIP Cleaning Log', 'Cleaning', 'Chemical Concentration', 'Number', 'Chemical Concentration', 'ppm', 'Daily', true, 'Advanced', 'Dairy'),
(24, 'CIP Cleaning Log', 'Cleaning', 'Staff', 'Text', '-', '-', 'Daily', true, 'Advanced', 'Dairy'),
(30, 'Meat Receiving Log', 'Receiving', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(30, 'Meat Receiving Log', 'Receiving', 'Condition Check', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(30, 'Meat Receiving Log', 'Receiving', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(31, 'Residue Testing Log', 'Receiving', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(31, 'Residue Testing Log', 'Receiving', 'Residue Level', 'Number', 'Residue', 'ppm', 'Each batch', true, 'Advanced', 'Meat'),
(31, 'Residue Testing Log', 'Receiving', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(32, 'Chilling Log', 'Cooling', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(32, 'Chilling Log', 'Cooling', 'Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Advanced', 'Meat'),
(32, 'Chilling Log', 'Cooling', 'Time', 'Time', 'Time', 'Hours', 'Each batch', true, 'Advanced', 'Meat'),
(32, 'Chilling Log', 'Cooling', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(33, 'Freezing Log', 'Cold Holding', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(33, 'Freezing Log', 'Cold Holding', 'Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Advanced', 'Meat'),
(33, 'Freezing Log', 'Cold Holding', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(34, 'Cutting Hygiene Log', 'Preparation', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(34, 'Cutting Hygiene Log', 'Preparation', 'Hygiene Check', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(34, 'Cutting Hygiene Log', 'Preparation', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(35, 'Grinding Control Log', 'Processing', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(35, 'Grinding Control Log', 'Processing', 'Process Control', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(35, 'Grinding Control Log', 'Processing', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Meat'),
(40, 'Brix Level Log', 'Processing', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(40, 'Brix Level Log', 'Processing', 'Brix Level', 'Number', 'Brix', '°Bx', 'Each batch', true, 'Advanced', 'Beverage'),
(40, 'Brix Level Log', 'Processing', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(41, 'pH Monitoring Log', 'Processing', 'Date', 'Date', '-', '-', 'Hourly', true, 'Advanced', 'Beverage'),
(41, 'pH Monitoring Log', 'Processing', 'pH Level', 'Number', 'pH', 'pH', 'Hourly', true, 'Advanced', 'Beverage'),
(41, 'pH Monitoring Log', 'Processing', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Advanced', 'Beverage'),
(42, 'Carbonation Pressure Log', 'Processing', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(42, 'Carbonation Pressure Log', 'Processing', 'Pressure', 'Number', 'Pressure', 'bar', 'Each batch', true, 'Advanced', 'Beverage'),
(42, 'Carbonation Pressure Log', 'Processing', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(43, 'Bottle Sterilization Log', 'Packaging', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(43, 'Bottle Sterilization Log', 'Packaging', 'Sterilization Check', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(43, 'Bottle Sterilization Log', 'Packaging', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'Beverage'),
(50, 'Turbidity Log', 'Processing', 'Date', 'Date', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(50, 'Turbidity Log', 'Processing', 'Turbidity', 'Number', 'Turbidity', 'NTU', 'Hourly', true, 'Advanced', 'Water'),
(50, 'Turbidity Log', 'Processing', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(51, 'TDS Log', 'Processing', 'Date', 'Date', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(51, 'TDS Log', 'Processing', 'TDS Level', 'Number', 'TDS', 'ppm', 'Hourly', true, 'Advanced', 'Water'),
(51, 'TDS Log', 'Processing', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(52, 'Microbial Testing Log', 'Processing', 'Date', 'Date', '-', '-', 'Daily', true, 'Advanced', 'Water'),
(52, 'Microbial Testing Log', 'Processing', 'Test Result', 'Text', 'Microbiology', NULL, 'Daily', true, 'Advanced', 'Water'),
(52, 'Microbial Testing Log', 'Processing', 'Staff', 'Text', '-', '-', 'Daily', true, 'Advanced', 'Water'),
(53, 'Chlorination Log', 'Processing', 'Date', 'Date', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(53, 'Chlorination Log', 'Processing', 'Chlorine Level', 'Number', 'Chlorine', 'ppm', 'Hourly', true, 'Advanced', 'Water'),
(53, 'Chlorination Log', 'Processing', 'Staff', 'Text', '-', '-', 'Hourly', true, 'Advanced', 'Water'),
(12, 'Allergen Control Log', 'Preparation', 'Date', 'Date', '-', '-', 'Daily', true, 'Core', 'All'),
(12, 'Allergen Control Log', 'Preparation', 'Allergen Type', 'Text', '-', '-', 'Daily', true, 'Core', 'All'),
(12, 'Allergen Control Log', 'Preparation', 'Control Measure', 'Text', '-', '-', 'Daily', true, 'Core', 'All'),
(12, 'Allergen Control Log', 'Preparation', 'Staff', 'Text', '-', '-', 'Daily', true, 'Core', 'All'),
(13, 'Reheating Log', 'Reheating', 'Date', 'Date', '-', '-', 'Each batch', true, 'Core', 'All'),
(13, 'Reheating Log', 'Reheating', 'Temperature', 'Number', 'Temperature', '°C', 'Each batch', true, 'Core', 'All'),
(13, 'Reheating Log', 'Reheating', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Core', 'All'),
(14, 'Equipment Maintenance Log', 'General', 'Date', 'Date', '-', '-', 'Monthly', true, 'Core', 'All'),
(14, 'Equipment Maintenance Log', 'General', 'Equipment Name', 'Text', '-', '-', 'Monthly', true, 'Core', 'All'),
(14, 'Equipment Maintenance Log', 'General', 'Maintenance Action', 'Text', '-', '-', 'Monthly', true, 'Core', 'All'),
(14, 'Equipment Maintenance Log', 'General', 'Staff', 'Text', '-', '-', 'Monthly', true, 'Core', 'All'),
(60, 'Packaging Inspection Log', 'Packaging', 'Date', 'Date', '-', '-', 'Each batch', true, 'Advanced', 'All'),
(60, 'Packaging Inspection Log', 'Packaging', 'Inspection Result', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'All'),
(60, 'Packaging Inspection Log', 'Packaging', 'Staff', 'Text', '-', '-', 'Each batch', true, 'Advanced', 'All');
