
INSERT INTO public.prp_mapping (activity, program_name) VALUES
('Restaurant', 'Cleaning and Sanitation Program'),
('Restaurant', 'Pest Control Program'),
('Restaurant', 'Personal Hygiene Program'),
('Restaurant', 'Supplier Control Program'),
('Restaurant', 'Waste Management Program'),
('Restaurant', 'Equipment Maintenance Program'),
('Restaurant', 'Allergen Control Program'),
('Restaurant', 'Document Control Program'),
('Restaurant', 'Record Keeping Program'),
('Restaurant', 'Training Program'),
('Restaurant', 'Internal Audit Program'),
('Cafe', 'Cleaning and Sanitation Program'),
('Cafe', 'Pest Control Program'),
('Cafe', 'Personal Hygiene Program'),
('Cafe', 'Supplier Control Program'),
('Cafe', 'Waste Management Program'),
('Cafe', 'Equipment Maintenance Program'),
('Cafe', 'Allergen Control Program'),
('Cafe', 'Document Control Program'),
('Cafe', 'Record Keeping Program'),
('Cafe', 'Training Program'),
('Cafe', 'Internal Audit Program'),
('Bakery', 'Cleaning and Sanitation Program'),
('Bakery', 'Pest Control Program'),
('Bakery', 'Personal Hygiene Program'),
('Bakery', 'Supplier Control Program'),
('Bakery', 'Waste Management Program'),
('Bakery', 'Equipment Maintenance Program'),
('Bakery', 'Allergen Control Program'),
('Bakery', 'Temperature Control Program'),
('Bakery', 'Document Control Program'),
('Bakery', 'Record Keeping Program'),
('Bakery', 'Training Program'),
('Bakery', 'Internal Audit Program'),
('Juice Bar', 'Cleaning and Sanitation Program'),
('Juice Bar', 'Pest Control Program'),
('Juice Bar', 'Personal Hygiene Program'),
('Juice Bar', 'Supplier Control Program'),
('Juice Bar', 'Waste Management Program'),
('Juice Bar', 'Equipment Maintenance Program'),
('Juice Bar', 'Temperature Control Program'),
('Juice Bar', 'Document Control Program'),
('Juice Bar', 'Record Keeping Program'),
('Juice Bar', 'Training Program'),
('Juice Bar', 'Internal Audit Program'),
('Ice Cream Shop', 'Cleaning and Sanitation Program'),
('Ice Cream Shop', 'Pest Control Program'),
('Ice Cream Shop', 'Personal Hygiene Program'),
('Ice Cream Shop', 'Supplier Control Program'),
('Ice Cream Shop', 'Equipment Maintenance Program'),
('Ice Cream Shop', 'Allergen Control Program'),
('Ice Cream Shop', 'Temperature Control Program'),
('Ice Cream Shop', 'Document Control Program'),
('Ice Cream Shop', 'Record Keeping Program'),
('Ice Cream Shop', 'Training Program'),
('Ice Cream Shop', 'Internal Audit Program'),
('Catering', 'Cleaning and Sanitation Program'),
('Catering', 'Pest Control Program'),
('Catering', 'Personal Hygiene Program'),
('Catering', 'Supplier Control Program'),
('Catering', 'Waste Management Program'),
('Catering', 'Equipment Maintenance Program'),
('Catering', 'Temperature Control Program'),
('Catering', 'Document Control Program'),
('Catering', 'Record Keeping Program'),
('Catering', 'Training Program'),
('Catering', 'Internal Audit Program'),
('Cloud Kitchen', 'Cleaning and Sanitation Program'),
('Cloud Kitchen', 'Pest Control Program'),
('Cloud Kitchen', 'Personal Hygiene Program'),
('Cloud Kitchen', 'Supplier Control Program'),
('Cloud Kitchen', 'Waste Management Program'),
('Cloud Kitchen', 'Equipment Maintenance Program'),
('Cloud Kitchen', 'Temperature Control Program'),
('Cloud Kitchen', 'Document Control Program'),
('Cloud Kitchen', 'Record Keeping Program'),
('Cloud Kitchen', 'Training Program'),
('Cloud Kitchen', 'Internal Audit Program'),
('Dairy', 'Cleaning and Sanitation Program'),
('Dairy', 'Pest Control Program'),
('Dairy', 'Personal Hygiene Program'),
('Dairy', 'Supplier Control Program'),
('Dairy', 'Waste Management Program'),
('Dairy', 'Equipment Maintenance Program'),
('Dairy', 'Allergen Control Program'),
('Dairy', 'Temperature Control Program'),
('Dairy', 'Process Control Program'),
('Dairy', 'Water Quality Control Program'),
('Dairy', 'Calibration Program'),
('Dairy', 'Traceability and Recall Program'),
('Dairy', 'Document Control Program'),
('Dairy', 'Record Keeping Program'),
('Dairy', 'Training Program'),
('Dairy', 'Internal Audit Program'),
('Meat', 'Cleaning and Sanitation Program'),
('Meat', 'Pest Control Program'),
('Meat', 'Personal Hygiene Program'),
('Meat', 'Supplier Control Program'),
('Meat', 'Waste Management Program'),
('Meat', 'Equipment Maintenance Program'),
('Meat', 'Temperature Control Program'),
('Meat', 'Process Control Program'),
('Meat', 'Calibration Program'),
('Meat', 'Traceability and Recall Program'),
('Meat', 'Document Control Program'),
('Meat', 'Record Keeping Program'),
('Meat', 'Training Program'),
('Meat', 'Internal Audit Program'),
('Beverage', 'Cleaning and Sanitation Program'),
('Beverage', 'Pest Control Program'),
('Beverage', 'Personal Hygiene Program'),
('Beverage', 'Supplier Control Program'),
('Beverage', 'Waste Management Program'),
('Beverage', 'Equipment Maintenance Program'),
('Beverage', 'Temperature Control Program'),
('Beverage', 'Process Control Program'),
('Beverage', 'Water Quality Control Program'),
('Beverage', 'Calibration Program'),
('Beverage', 'Traceability and Recall Program'),
('Beverage', 'Document Control Program'),
('Beverage', 'Record Keeping Program'),
('Beverage', 'Training Program'),
('Beverage', 'Internal Audit Program'),
('Water', 'Cleaning and Sanitation Program'),
('Water', 'Pest Control Program'),
('Water', 'Personal Hygiene Program'),
('Water', 'Equipment Maintenance Program'),
('Water', 'Water Quality Control Program'),
('Water', 'Process Control Program'),
('Water', 'Calibration Program'),
('Water', 'Traceability and Recall Program'),
('Water', 'Document Control Program'),
('Water', 'Record Keeping Program'),
('Water', 'Training Program'),
('Water', 'Internal Audit Program');
