DELETE FROM process_hazard_map;
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (1, 1, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (2, 1, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (3, 1, 25);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (4, 1, 30);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (5, 1, 45);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (6, 2, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (7, 2, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (8, 2, 31);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (9, 3, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (10, 3, 2);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (11, 3, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (12, 3, 15);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (13, 4, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (14, 4, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (15, 5, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (16, 5, 15);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (17, 5, 25);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (18, 6, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (19, 6, 4);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (20, 6, 26);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (21, 6, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (22, 7, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (23, 7, 7);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (24, 7, 17);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (25, 8, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (26, 8, 46);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (27, 8, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (28, 9, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (29, 9, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (30, 10, 42);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (31, 10, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (32, 11, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (33, 11, 26);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (34, 11, 29);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (35, 11, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (36, 12, 26);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (37, 12, 29);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (38, 12, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (39, 13, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (40, 13, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (41, 13, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (42, 14, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (43, 14, 26);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (44, 14, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (45, 15, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (46, 15, 26);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (47, 15, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (48, 16, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (49, 16, 5);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (50, 16, 6);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (51, 16, 18);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (52, 17, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (53, 17, 18);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (54, 18, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (55, 18, 18);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (56, 19, 5);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (57, 19, 6);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (58, 19, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (59, 20, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (60, 20, 2);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (61, 21, 2);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (62, 21, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (63, 22, 1);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (64, 22, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (65, 23, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (66, 23, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (67, 24, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (68, 25, 2);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (69, 26, 2);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (70, 27, 31);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (71, 28, 31);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (72, 29, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (73, 29, 42);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (74, 29, 43);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (75, 29, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (76, 30, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (77, 30, 43);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (78, 30, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (79, 31, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (80, 31, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (81, 32, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (82, 32, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (83, 33, 42);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (84, 33, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (85, 34, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (86, 35, 12);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (87, 35, 49);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (88, 36, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (89, 36, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (90, 37, 14);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (91, 38, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (92, 38, 19);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (93, 38, 20);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (94, 39, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (95, 39, 45);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (96, 40, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (97, 41, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (98, 42, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (99, 43, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (100, 43, 19);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (101, 44, 37);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (102, 45, 38);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (103, 46, 41);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (104, 47, 36);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (105, 48, 35);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (106, 49, 35);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (107, 50, 21);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (108, 51, 37);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (109, 52, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (110, 52, 19);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (111, 53, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (112, 53, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (113, 53, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (114, 54, 3);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (115, 54, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (116, 55, 29);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (117, 55, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (118, 56, 13);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (119, 56, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (120, 57, 29);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (121, 57, 51);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (122, 58, 11);
INSERT INTO process_hazard_map (id, process_id, hazard_id) VALUES (123, 58, 31);

DELETE FROM ccp_table;
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (1, 16, 1, 5, 3, 15, 'CCP', '≥75°C core temperature', 'Temperature monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (2, 16, 5, 4, 3, 12, 'CCP', '≥75°C core temperature', 'Temperature monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (3, 16, 6, 4, 3, 12, 'CCP', '≥75°C core temperature', 'Temperature monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (4, 19, 5, 4, 3, 12, 'CCP', 'Cool to ≤5°C within 6 hours', 'Time & temperature monitoring', 'Adjust cooling');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (5, 19, 6, 4, 3, 12, 'CCP', 'Cool to ≤5°C within 6 hours', 'Time & temperature monitoring', 'Adjust cooling');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (6, 19, 13, 4, 3, 12, 'CCP', 'Cool to ≤5°C within safe time', 'Time & temperature monitoring', 'Adjust cooling');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (7, 20, 13, 5, 3, 15, 'CCP', '≥60°C holding temperature', 'Temperature monitoring', 'Adjust temperature');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (8, 21, 2, 5, 3, 15, 'CCP', '≤5°C storage temperature', 'Temperature log', 'Adjust temperature');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (9, 21, 13, 4, 3, 12, 'CCP', '≤5°C storage temperature', 'Temperature log', 'Adjust temperature');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (10, 22, 1, 5, 3, 15, 'CCP', '≥75°C reheating temperature', 'Temperature check', 'Reheat or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (11, 36, 13, 5, 3, 15, 'CCP', '≤5°C or ≥60°C during transport', 'Temperature monitoring', 'Adjust transport conditions');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (12, 17, 1, 5, 3, 15, 'CCP', '≥72°C for 15 sec', 'Temperature monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (13, 17, 18, 4, 3, 12, 'CCP', '≥72°C for required time', 'Temperature monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (14, 18, 1, 5, 3, 15, 'CCP', 'UHT conditions applied', 'Process monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (15, 18, 18, 4, 3, 12, 'CCP', 'UHT conditions applied', 'Process monitoring', 'Reprocess or discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (16, 33, 42, 4, 2, 8, 'OPRP', 'Metal detector operational', 'Equipment check', 'Stop line');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (17, 29, 14, 4, 2, 8, 'OPRP', 'Hygienic filling conditions', 'Visual inspection', 'Repack / discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (18, 30, 43, 3, 2, 6, 'OPRP', 'Packaging integrity maintained', 'Visual inspection', 'Remove defects');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (19, 30, 14, 4, 2, 8, 'OPRP', 'Hygienic packaging conditions', 'Visual inspection', 'Repack / discard');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (20, 6, 26, 4, 2, 8, 'OPRP', 'Allergen control procedure', 'Visual check', 'Clean and correct');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (21, 1, 30, 4, 3, 12, 'OPRP', 'Approved suppliers only', 'Supplier check', 'Reject batch');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (22, 1, 25, 3, 3, 9, 'OPRP', 'Raw material inspection', 'Visual check', 'Reject batch');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (23, 38, 3, 5, 3, 15, 'CCP', 'Microbiological limits compliance', 'Water testing', 'Stop intake');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (24, 38, 19, 4, 3, 12, 'CCP', 'Microbial limits within standard', 'Lab testing', 'Stop process');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (25, 43, 3, 4, 3, 12, 'CCP', 'Effective filtration', 'Process monitoring', 'Adjust / backwash');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (26, 48, 35, 5, 3, 15, 'CCP', 'Chlorine 0.2–0.5 ppm', 'Chlorine testing', 'Adjust dosing');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (27, 50, 21, 4, 3, 12, 'CCP', 'Clean storage tank', 'Inspection', 'Clean tank');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (28, 45, 38, 4, 2, 8, 'OPRP', 'RO system integrity', 'Pressure monitoring', 'Stop system');
INSERT INTO ccp_table (id, process_id, hazard_id, severity, likelihood, risk_score, default_control_type, critical_limit, monitoring, corrective_action) VALUES (29, 47, 36, 4, 2, 8, 'OPRP', 'pH within limits', 'pH monitoring', 'Adjust dosing');

DELETE FROM decision_tree_questions;
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (1, 'Restaurant', 'Do you thaw frozen ingredients before cooking?', 'Thawing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (2, 'Restaurant', 'Do you wash fruits or vegetables before preparation?', 'Washing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (3, 'Restaurant', 'Do you cook food before serving?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (4, 'Restaurant', 'Do you keep food hot before serving?', 'Hot Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (5, 'Restaurant', 'Do you store ready-to-eat food under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (6, 'Restaurant', 'Do you cool cooked food for later use?', 'Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (7, 'Restaurant', 'Do you reheat cooked food before serving?', 'Reheating');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (8, 'Cafe', 'Do you mix ingredients to prepare beverages?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (9, 'Cafe', 'Do you cook or heat food items?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (10, 'Cafe', 'Do you keep hot food in displays?', 'Hot Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (11, 'Cafe', 'Do you store products under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (12, 'Cafe', 'Do you wash fruits used in drinks?', 'Washing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (13, 'Juice Bar', 'Do you wash fruits or vegetables before processing?', 'Washing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (14, 'Juice Bar', 'Do you prepare ingredients before processing?', 'Preparation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (15, 'Juice Bar', 'Do you mix or blend ingredients?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (16, 'Juice Bar', 'Do you store products under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (17, 'Ice Cream Shop', 'Do you mix ingredients to prepare products?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (18, 'Ice Cream Shop', 'Do you store products under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (19, 'Ice Cream Shop', 'Do you prepare products before serving?', 'Preparation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (20, 'Catering', 'Do you thaw frozen ingredients before preparation?', 'Thawing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (21, 'Catering', 'Do you cook food before service?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (22, 'Catering', 'Do you cool cooked food before service?', 'Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (23, 'Catering', 'Do you transport food to another location?', 'Transportation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (24, 'Catering', 'Do you reheat food before serving?', 'Reheating');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (25, 'Catering', 'Do you keep food hot before serving?', 'Hot Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (26, 'Catering', 'Do you store food under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (27, 'Catering', 'Do you package food before delivery?', 'Packaging');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (28, 'Cloud Kitchen', 'Do you thaw frozen ingredients before cooking?', 'Thawing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (29, 'Cloud Kitchen', 'Do you cook food before packaging?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (30, 'Cloud Kitchen', 'Do you cool cooked food before packaging?', 'Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (31, 'Cloud Kitchen', 'Do you store food under refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (32, 'Cloud Kitchen', 'Do you keep food hot before dispatch?', 'Hot Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (33, 'Cloud Kitchen', 'Do you package food before delivery?', 'Packaging');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (34, 'Cloud Kitchen', 'Do you transport food for delivery?', 'Transportation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (35, 'Bakery', 'Do you mix ingredients to prepare products?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (36, 'Bakery', 'Do you bake products?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (37, 'Bakery', 'Do you cool products before packaging?', 'Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (38, 'Bakery', 'Do your products require refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (39, 'Bakery', 'Do you package products before sale?', 'Packaging');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (40, 'Pastry Shop', 'Do you mix ingredients to prepare products?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (41, 'Pastry Shop', 'Do you bake products?', 'Cooking / Baking');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (42, 'Pastry Shop', 'Do you cool products before packaging?', 'Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (43, 'Pastry Shop', 'Do your products require refrigeration?', 'Cold Holding');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (44, 'Pastry Shop', 'Do you package products before sale?', 'Packaging');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (45, 'Dairy Processing', 'Do you perform separation?', 'Separation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (46, 'Dairy Processing', 'Do you perform fermentation?', 'Fermentation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (47, 'Dairy Processing', 'Do you perform coagulation?', 'Coagulation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (48, 'Dairy Processing', 'Do you perform cutting or handling?', 'Cutting / Deboning');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (49, 'Dairy Processing', 'Do you perform aging or ripening?', 'Aging / Ripening');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (50, 'Dairy Processing', 'Do you concentrate or dry products?', 'Evaporation / Concentration | Drying');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (51, 'Dairy Processing', 'Do you produce frozen products?', 'Frozen Storage');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (52, 'Meat Processing', 'Do you thaw frozen meat?', 'Thawing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (53, 'Meat Processing', 'Do you perform cutting or deboning?', 'Cutting / Deboning');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (54, 'Meat Processing', 'Do you perform grinding or mincing?', 'Grinding / Mincing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (55, 'Meat Processing', 'Do you mix ingredients or additives?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (56, 'Meat Processing', 'Do you form products?', 'Forming / Shaping');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (57, 'Meat Processing', 'Do you marinate or cure products?', 'Marination | Curing');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (58, 'Meat Processing', 'Do you cook products?', 'Cooking / Baking | Cooling');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (59, 'Meat Processing', 'Do you produce frozen products?', 'Freezing | Frozen Storage');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (60, 'Juice & Beverage Processing', 'Do you process fresh fruits?', 'Washing | Sorting / Grading | Peeling | Cutting | Juice Extraction');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (61, 'Juice & Beverage Processing', 'Do you perform filtration?', 'Filtration');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (62, 'Juice & Beverage Processing', 'Do you mix ingredients?', 'Mixing / Blending');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (63, 'Juice & Beverage Processing', 'Do you add ingredients?', 'Addition of Ingredients');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (64, 'Juice & Beverage Processing', 'Do you perform pasteurization?', 'Pasteurization');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (65, 'Juice & Beverage Processing', 'Do you carbonate beverages?', 'Carbonation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (66, 'Juice & Beverage Processing', 'Do you store products under refrigeration?', 'Cold Storage');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (67, 'Water Treatment', 'Do you perform coagulation and flocculation?', 'Coagulation (Water) | Flocculation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (68, 'Water Treatment', 'Do you perform sedimentation?', 'Sedimentation');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (69, 'Water Treatment', 'Do you perform filtration?', 'Filtration');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (70, 'Water Treatment', 'Do you use activated carbon filtration?', 'Activated Carbon Filtration');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (71, 'Water Treatment', 'Do you use reverse osmosis?', 'Reverse Osmosis (RO)');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (72, 'Water Treatment', 'Do you perform softening?', 'Softening');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (73, 'Water Treatment', 'Do you adjust pH?', 'Chemical Dosing (pH Adjustment)');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (74, 'Water Treatment', 'Do you disinfect water?', 'Disinfection (Chlorination / UV / Ozone)');
INSERT INTO decision_tree_questions (id, activity, question, related_process) VALUES (75, 'Water Treatment', 'Do you perform dechlorination?', 'Dechlorination');

SELECT setval('process_hazard_map_id_seq', COALESCE((SELECT MAX(id) FROM process_hazard_map), 0) + 1, false);
SELECT setval('ccp_table_id_seq', COALESCE((SELECT MAX(id) FROM ccp_table), 0) + 1, false);
SELECT setval('decision_tree_questions_id_seq', COALESCE((SELECT MAX(id) FROM decision_tree_questions), 0) + 1, false);