
INSERT INTO public.logs_mapping (activity, process_step, log_name) VALUES
('Restaurant', 'Receiving', 'Receiving Log'),
('Restaurant', 'Preparation', 'Cleaning Log'),
('Restaurant', 'Cooking / Baking', 'CCP Monitoring Log'),
('Restaurant', 'Cooking / Baking', 'Cooking Temperature Log'),
('Restaurant', 'Cooling', 'Cooling Log'),
('Restaurant', 'Cold Holding', 'Cold Storage Log'),
('Restaurant', 'Hot Holding', 'Hot Holding Log'),
('Restaurant', 'Storage', 'Pest Control Log'),
('Restaurant', 'General', 'Corrective Action Log'),
('Restaurant', 'General', 'Internal Audit Log'),
('Restaurant', 'General', 'Training Log'),
('Bakery', 'Receiving', 'Receiving Log'),
('Bakery', 'Preparation', 'Cleaning Log'),
('Bakery', 'Mixing', 'Grinding Control Log'),
('Bakery', 'Cooking / Baking', 'Cooking Temperature Log'),
('Bakery', 'Cooling', 'Cooling Log'),
('Bakery', 'Packaging', 'Packaging Inspection Log'),
('Bakery', 'Storage', 'Pest Control Log'),
('Bakery', 'General', 'Corrective Action Log'),
('Bakery', 'General', 'Internal Audit Log'),
('Bakery', 'General', 'Training Log'),
('Catering', 'Receiving', 'Receiving Log'),
('Catering', 'Preparation', 'Cleaning Log'),
('Catering', 'Cooking / Baking', 'Cooking Temperature Log'),
('Catering', 'Hot Holding', 'Hot Holding Log'),
('Catering', 'Transportation', 'Hot Holding Log'),
('Catering', 'General', 'Corrective Action Log'),
('Catering', 'General', 'Internal Audit Log'),
('Catering', 'General', 'Training Log'),
('Cloud Kitchen', 'Receiving', 'Receiving Log'),
('Cloud Kitchen', 'Preparation', 'Cleaning Log'),
('Cloud Kitchen', 'Cooking / Baking', 'Cooking Temperature Log'),
('Cloud Kitchen', 'Hot Holding', 'Hot Holding Log'),
('Cloud Kitchen', 'General', 'Corrective Action Log'),
('Cloud Kitchen', 'General', 'Internal Audit Log'),
('Cloud Kitchen', 'General', 'Training Log'),
('Dairy', 'Receiving', 'Milk Receiving Log'),
('Dairy', 'Cold Holding', 'Milk Storage Temperature Log'),
('Dairy', 'Processing', 'Pasteurization Temperature Log'),
('Dairy', 'Processing', 'Pasteurization Time Log'),
('Dairy', 'Processing', 'Fermentation pH Log'),
('Dairy', 'Cleaning', 'CIP Cleaning Log'),
('Dairy', 'General', 'Corrective Action Log'),
('Dairy', 'General', 'Internal Audit Log'),
('Dairy', 'General', 'Training Log'),
('Meat', 'Receiving', 'Meat Receiving Log'),
('Meat', 'Receiving', 'Residue Testing Log'),
('Meat', 'Cooling', 'Chilling Log'),
('Meat', 'Cold Holding', 'Freezing Log'),
('Meat', 'Preparation', 'Cutting Hygiene Log'),
('Meat', 'Processing', 'Grinding Control Log'),
('Meat', 'General', 'Corrective Action Log'),
('Meat', 'General', 'Internal Audit Log'),
('Meat', 'General', 'Training Log'),
('Beverage', 'Processing', 'Brix Level Log'),
('Beverage', 'Processing', 'pH Monitoring Log'),
('Beverage', 'Processing', 'Carbonation Pressure Log'),
('Beverage', 'Packaging', 'Bottle Sterilization Log'),
('Beverage', 'General', 'Corrective Action Log'),
('Beverage', 'General', 'Internal Audit Log'),
('Beverage', 'General', 'Training Log'),
('Water', 'Processing', 'Turbidity Log'),
('Water', 'Processing', 'TDS Log'),
('Water', 'Processing', 'Microbial Testing Log'),
('Water', 'Processing', 'Chlorination Log'),
('Water', 'General', 'Corrective Action Log'),
('Water', 'General', 'Internal Audit Log'),
('Water', 'General', 'Training Log');

INSERT INTO public.fsms_documents (document_name, description, responsible) VALUES
('Food Safety Policy', 'The organization is committed to producing safe food by implementing HACCP principles, maintaining hygiene standards, and complying with food safety regulations', 'Owner'),
('Food Safety Objectives', 'The organization aims to maintain safe food production, monitor critical control points, and continuously improve food safety performance', 'Owner'),
('HACCP Team', 'The HACCP team is responsible for developing, implementing, and maintaining the HACCP system within the organization', 'Manager'),
('Product Description', 'Description of food products including ingredients, storage conditions, and shelf life', 'Manager'),
('Intended Use', 'Description of how the food product is expected to be used by consumers', 'Manager'),
('Flow Diagram Verification', 'Procedure for verifying that the process flow diagram accurately represents the food preparation process', 'Manager'),
('HACCP Verification Procedure', 'Procedures used to verify that the HACCP system is working effectively', 'Manager'),
('Record Keeping Procedure', 'Procedure for maintaining and storing food safety records and monitoring logs', 'Manager'),
('Corrective Action Procedure', 'Steps taken when monitoring results indicate a deviation from critical limits', 'Manager'),
('Internal Audit Procedure', 'Procedure for conducting internal food safety audits within the organization', 'Manager'),
('Product Recall Procedure', 'Procedure for identifying, tracing, and removing unsafe or non-compliant food products from sale or distribution. The organization will immediately stop using the affected product, isolate the batch, inform management, and take corrective actions to protect consumer safety. Records of the recall and actions taken will be maintained.', 'Manager'),
('Supplier Approval Procedure', 'Procedure for evaluating, approving, and monitoring suppliers to ensure raw material safety and compliance', 'QA Manager'),
('Approved Supplier List', 'List of approved suppliers who meet food safety and quality requirements', 'QA Manager'),
('Raw Material Specification', 'Specifications for raw materials including safety, quality, and acceptance criteria', 'QA Manager'),
('Traceability Procedure', 'Procedure for tracking raw materials and finished products through all stages of production', 'QA Manager'),
('Batch Coding System', 'System for assigning batch numbers to products for identification and traceability', 'Production Manager'),
('Product Identification Procedure', 'Procedure for labeling and identifying products throughout production and distribution', 'Production Manager'),
('Allergen Control Procedure', 'Procedure for identifying, managing, and preventing allergen cross-contact', 'QA Manager'),
('Allergen Risk Assessment', 'Assessment of allergen risks associated with raw materials and processing steps', 'QA Manager'),
('Allergen Cleaning Validation', 'Procedure for validating cleaning effectiveness to remove allergen residues', 'QA Manager'),
('Calibration Procedure', 'Procedure for calibrating equipment such as thermometers, pH meters, and sensors', 'Maintenance Manager'),
('Calibration Records Template', 'Template for recording calibration results and maintaining equipment accuracy', 'Maintenance Manager'),
('Equipment Verification Procedure', 'Procedure to verify equipment performance and functionality before use', 'Maintenance Manager'),
('Preventive Maintenance Procedure', 'Procedure for scheduled maintenance to ensure equipment reliability', 'Maintenance Manager'),
('Equipment Maintenance Log', 'Log for recording maintenance activities and equipment repairs', 'Maintenance Manager'),
('Breakdown Handling Procedure', 'Procedure for managing equipment breakdowns and minimizing production risks', 'Maintenance Manager'),
('Cleaning and Sanitation Procedure', 'Procedure for cleaning and sanitizing equipment and facilities', 'QA Manager'),
('Cleaning Schedule', 'Schedule for routine cleaning and sanitation activities', 'Production Manager'),
('Chemical Control Procedure', 'Procedure for handling, storing, and using cleaning chemicals safely', 'QA Manager'),
('Pest Control Procedure', 'Procedure for monitoring and controlling pests within the facility', 'QA Manager'),
('Pest Monitoring Records', 'Records of pest control inspections and corrective actions', 'QA Manager'),
('Training Procedure', 'Procedure for training staff on food safety and operational practices', 'HR / Training Officer'),
('Competency Assessment', 'Procedure for evaluating staff competence and performance', 'HR / Training Officer'),
('Training Plan', 'Planned schedule of training activities for employees', 'HR / Training Officer'),
('Non-Conformance Procedure', 'Procedure for identifying and managing non-conforming products or processes', 'QA Manager'),
('Product Hold & Release Procedure', 'Procedure for holding and releasing products based on quality and safety checks', 'QA Manager'),
('Document Control Procedure', 'Procedure for managing and updating documents within the system', 'QA Manager'),
('Record Control Procedure', 'Procedure for maintaining and storing records securely and effectively', 'QA Manager'),
('Risk Assessment Procedure', 'Procedure for assessing risks related to food safety hazards', 'QA Manager'),
('Hazard Evaluation Methodology', 'Methodology used to evaluate hazards based on severity and likelihood', 'QA Manager');
